### ISSUE TITLE
Fix documentation in dialects/exasol.md on ORDER BY 

### ISSUE THREAD

**Issue by PeggySchmidtMittenzwei** [exasol/exasol-virtual-schema#104]
Currently [VSEXA User guide](https://github.com/exasol/exasol-virtual-schema/blob/main/doc/dialects/exasol.md) contains wrong information:
```sql
SELECT * FROM (<virtual-schema-query>) ORDER BY <criteria> [, ...]
```

Because Exasol SQL engine might push down the keyword `ORDER BY` to the foreign database accessed by the virtual-schema sub-query. To prevent the push-down users can add an additional clause `ORDER BY FALSE` inside the sub-query:

```sql
SELECT * FROM (<virtual-schema-query> ORDER BY FALSE) ORDER BY <criteria> [, ...]
```

The outer clause `ORDER BY` will then be evaluated in the Exasol database domain. 

Please note that clause `ORDER BY FALSE` needs to be used exactly as specified, while variants like `ORDER BY TRUE` or `ORDER BY 'a'` will have no effect.

As @narmion says: alternatively in statement [`CREATE VIRTUAL SCHEMA`](https://github.com/exasol/exasol-virtual-schema/blob/main/doc/dialects/exasol.md#creating-a-local-virtual-schema) you can add parameter `EXCLUDED_CAPABILITIES='ORDER_BY_COLUMN, ORDER_BY_EXPRESSION'`, see [Exasol documentation](https://docs.exasol.com/db/latest/database_concepts/virtual_schema/adapter_properties.htm).

However both approaches still come with some limitations regarding collations and order by limit clauses.

#### Collations

A _collation_ is a set of rules that defines how to compare and sort character strings.

The foreign database accessed by the virtual-schema-sub-query might support different collations while Exasol database only supports collations `UTF-8` and `ASCII`. 

When clause `ORDER BY` is not pushed-down but executed in the Exasol database domain then only the Exasol collation will be applied. This can change the order of the rows in the result set.

#### Order by limit

With clause `ORDER BY LIMIT <n>` the SQL statement returns max. only the first `<n>` rows ignoring all following rows of the result set.

Both approaches described above prevent the push-down of clause `ORDER BY LIMIT` inside the virtual-schema sub-query. In effect the sub-query then returns the complete result set which might be much larger than the specified limit `<n>` which can have significant effects on the volume of data transfer and the runtime of the query.

### Acceptance Criteria
1. Wrong passage in [VSEXA dialect guide](https://github.com/exasol/exasol-virtual-schema/blob/main/doc/dialects/exasol.md) is replaced by a link to known limitations in official Exasol documentation on [virtual schemas](https://docs.exasol.com/db/latest/database_concepts/virtual_schemas.htm).

**Comment by narmion** [comment]
Another workaround would be to set EXCLUDED_CAPABILITIES='ORDER_BY_COLUMN, ORDER_BY_EXPRESSION' if the adapter supports it.

**Comment by ckunki** [comment]
Additional information from @narmion: 
* Note no. 1: The reported problem only occurs if Exasol SQL engine can push-down the complete sub-query to the foreign datebase. As soon as there is a missing capability or any other feature that cannot be pushed-down the problem cannot be observed.
* Note no 2: Deeper nested sub-queries inside the virtual-schema-sub-query still can use collations available in the foreign datebase as well as clause `ORDER BY LIMIT` without problems.
* Note no 3: Clause `ORDER BY FALSE` is a workaround specific to Exasol SQL dialect and needs to be used  exactly as specified. Variants like `ORDER BY TRUE` or `ORDER BY 'a'` will have no effect.

**Comment by ckunki** [comment]
Marked as blocked until alignment with @redcatbear

**Comment by ckunki** [comment]
Based on the results in other tickets I propose to update VSEXA documentation as follows:

> The protocol used by ExaLoader (the part that runs the `IMPORT`) and Exasol core database only supports unordered transfer. Therefore the outermost order of the imported result rows is not guaranteed.
>
> If you need ordering, please wrap your query into an extra `SELECT * FROM (<virtual-schema-query> ORDER BY FALSE) ORDER BY <criteria> [, ...]` which will then be executed on the target Exasol database instead of the source of the virtual schema.
>
> Please note that clause `ORDER BY FALSE` needs to be used exactly as specified, while variants like `ORDER BY TRUE` or `ORDER BY 'a'` will have no effect.

Additionally I want to state my current understanding of the impact of the described limitation of the protocol:
* Besides VSEXA and VSORA rather all virtual schemas are impacted.
* In VSEXA not only EXA Connection but all connections are impacted.
* Document-based virtual schemas probably are not impacted as they usually do not support capability `ORDER BY` and hence the clause cannot be pushed down.

**Comment by redcatbear** [comment]
Okay from my side, if you verify the third statement in the code. Please check the implementation and remove "probably" if true.

**Comment by ckunki** [comment]
Current state of knowledge is that Document-based virtual schemas do not support capability ORDER_BY, see https://github.com/exasol/virtual-schema-common-document/blob/main/src/main/java/com/exasol/adapter/document/DocumentAdapter.java#L31

**Comment by ckunki** [comment]
Strategy found, described and aligned - removing blocker, starting implementation.
