### ISSUE TITLE
Update tests to include Exasol V8/ Update to vsjdbc 12.0.0 (VSEXA)

### ISSUE THREAD

**Issue by ckunki** [exasol/exasol-virtual-schema#105]
Since 2023-10-12 for version 8.23.0 of Exasol database a Docker image is available on [Dockerhub](https://hub.docker.com/layers/exasol/docker-db/8.23.0/images/sha256-c12588af953c73bcdd344d1b7cba6aea7fb709e09e97814664c4e16e87f77b73?context=explore)

The current ticket therefore requests to update the integration tests of VSEXA to use version 8.23.0 as latest default version.

Please note sibling-tickets for all [JDBC-based virtual schemas](https://github.com/exasol/virtual-schemas/blob/main/doc/user-guide/dialects.md).

**Comment by ckunki** [comment]
Waiting for update of VSCJDBC

**Comment by ckunki** [comment]
Switch `...` is only available with connection `IMPORT FROM EXA`.

**Comment by pj-spoelders** [comment]
Waiting for response on IS_LOCAL select statement clash with strict datatype checking in case of varchar ascii or char ascii datatypes
