### ISSUE TITLE
Remove Maven Central deployment

### ISSUE THREAD

**Issue by kaklakariada** [exasol/exasol-virtual-schema#122]
This project is currently published to Maven Central for each release. But it is not intended to be used as a library. To avoid overhead we should update the build and remove the deployment.

**Comment by pj-spoelders** [comment]
Let's wait with this until everyone of the team had the opportunity to see your internal message about this.

**Comment by redcatbear** [comment]
There is a good reason for this: EVSJ serves as basis for RLSJ.
