### ISSUE TITLE
Double check the supported capabilities 

### ISSUE THREAD

**Issue by chiaradiamarcelo** [exasol/exasol-virtual-schema#28]
It seems there might be some functions missing from the supported capabilites, for example the aggregate function ANY.

A list of all aggregate functions available in Exasol can be found at https://docs.exasol.com/sql_references/functions/aggregatefunctions.htm

We should double check that we cover them all

**Comment by AnastasiiaSergienko** [comment]
We've just done this a month ago. You can check the functions that are not supported in the documentation. For ANY we use SOME instead. Other unsupported functions have their reasons to be unsupported

https://github.com/exasol/virtual-schema-common-java/blob/master/doc/development/api/aggregate_functions_api.md
https://github.com/exasol/virtual-schema-common-java/blob/master/doc/development/api/scalar_functions_api.md
