### ISSUE TITLE
Explain how to disable TLS in connections with 7.0.x or older

### ISSUE THREAD

**Issue by redcatbear** [exasol/exasol-virtual-schema#57]
## Situation

When connecting an Exasol VS with an up-to-date JDBC driver, that driver expects the connection to be established via TLS. Exasol 7.1 was the first server version that supported JDBC over TLS.
This means that for connections to pre-7.1 instances TLS must be manually disabled.

## Acceptance Criteria

1. Installation instructions contain a section that explains how to disable TLS in a connection to pre-7.1 Exasol

**Comment by allipatev** [comment]
> Exasol 7.1 was the first **server** version that supported JDBC over TLS.

^^ That might be incorrect.

See [EXASOL-2936](https://www.exasol.com/support/browse/EXASOL-2936):

> Exasol driver-initiated connections (i.e. non-WebSocket connections) are supported in Exasol and all Exasol drivers as of version 7.1.0. Additionally, support for Exasol driver-initiated connections has been added to Exasol versions 6.2.15+ and 7.0.10+.
