### ISSUE TITLE
GEOMETRY, HASHTYPE, and INTERVAL data types not working as expected

### ISSUE THREAD

**Issue by exanm** [exasol/exasol-virtual-schema#66]
The latest release https://github.com/exasol/exasol-virtual-schema/releases/tag/6.0.0 contains changes for the data types HASHTYPE, GEOMETRY, INTERVAL DAY TO SECOND, and INTERVAL YEAR TO MONTH. The generated pushdown queries for these data types are not as expected:
- For `GEOMETRY` columns the adapter generates `IMPORT INTO (c1 GEOMETRY(2000000)) FROM JDBC ...`, but 2000000 is not the correct srid.
- For `HASHTYPE` columns with a size other than 16 bytes (the default) the adapter generates `IMPORT INTO (c1 HASHTYPE(16 byte)) ...`, but `16 byte` is wrong here, causing the query to fail with the error "data exception - Invalid hash format".
- For `INTERVAL DAY TO SECOND` and `INTERVAL YEAR TO MONTH` columns the adapter generates the same VARCHAR IMPORTS as the previous version, but the release notes say that there was a change.

**Comment by kaklakariada** [comment]
Due to restrictions of the JDBC driver we currently can't fix this for all data types. However we fixed the mapping of `HASHTYPE` in #70. `GEOMETRY` and `INTERVAL` types are mapped to `VARCHAR` as before, we reverted the behavior in #67.

**Comment by kaklakariada** [comment]
We fixed mapping of `HASHTYPE` in #69. The fix for `GEOMETRY` and `INTERVAL` will be done in #71.
