### ISSUE TITLE
Speedup reading of column metadata

### ISSUE THREAD

**Issue by exaSR** [exasol/exasol-virtual-schema#91]
Using the default implementation of virtual-schema-jdbc for reading column metadata is very slow with Exasol.
Reading all column data in a single operation and then matching them to tables locally should be a lot faster.

**Comment by redcatbear** [comment]
Fun fact: after a quick check of the code of the Lua variant (which I wrote, but that was too long ago to remember this detail) it looks like the Lua variant uses that optimization already. Including the table filter:
https://github.com/exasol/exasol-virtual-schema-common-lua/blob/c18cc4e70fe799c67d3d84597833df3299f30377/src/exasol/evscl/AbstractMetadataReader.lua#L179

**Comment by redcatbear** [comment]
Shelving.
